### ISSUE TITLE
请问你们这个按钮的变色是如何做的

### ISSUE THREAD

**Issue by dd1994** [imweb/sheral#5]
<img width="242" alt="screen shot 2016-09-27 at 16 38 05" src="https://cloud.githubusercontent.com/assets/4121510/18866100/e6db8e4e-84d0-11e6-8b46-6e05263020cf.png">

就是点按钮的时候会有个变色，看了下代码并没有用 js 绑定点击事件，这个点击变色是如何做的呢？

**Comment by marvin1023** [comment]
默认是用了:hover和:active伪类，可以通过sandal中的变量$activeStateSwitch来控制是否启用该样式
