### ISSUE TITLE
这东西只是你们内部玩的？

### ISSUE THREAD

**Issue by OYsun** [imweb/sheral#6]
纵览了一遍，发现只有演示demo和源码分析文章，却没有最重要的使用文档。作为一个css样式库，我都不知道在demo演示的那些组件用了什么css类，我还得看自己看源码，这叫人如何愉快的使用？好的开源产品首先是让人容易上手，有良好的文档，不是写一堆看起来高大上的源码教程。

**Comment by miniflycn** [comment]
@marvin1023
